/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.*;

import clases.Conexion;

import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 *
 * @author moise
 */
public class CrearMeta extends javax.swing.JFrame {

   /**
    * Creates new form CrearMeta
    */

   private JTextField txtNombre;
   private JTextArea txtDescripcion;
   private JTextField txtObjetivo;
   private JTextField txtAnio;
   private JButton btnGuardar;

   public CrearMeta() {
      initComponents();
      getContentPane().setBackground(new Color(60, 63, 65));
      setTitle("Registrar Nueva Meta");
      setSize(400, 350);
      setLocationRelativeTo(null);
      setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      setLayout(null);

      JLabel lblNombre = new JLabel("Nombre:");
      lblNombre.setForeground(Color.WHITE);
      lblNombre.setBounds(20, 20, 100, 20);
      add(lblNombre);

      txtNombre = new JTextField();
      txtNombre.setBounds(120, 20, 240, 25);
      add(txtNombre);

      JLabel lblDescripcion = new JLabel("Descripción:");
      lblDescripcion.setForeground(Color.white);
      lblDescripcion.setBounds(20, 60, 100, 20);
      add(lblDescripcion);

      txtDescripcion = new JTextArea();
      JScrollPane scroll = new JScrollPane(txtDescripcion);
      scroll.setBounds(120, 60, 240, 60);
      add(scroll);

      JLabel lblObjetivo = new JLabel("Objetivo:");
      lblObjetivo.setForeground(Color.white);
      lblObjetivo.setBounds(20, 130, 100, 20);
      add(lblObjetivo);

      txtObjetivo = new JTextField();
      txtObjetivo.setBounds(120, 130, 240, 25);
      add(txtObjetivo);

      JLabel lblAnio = new JLabel("Año:");
      lblAnio.setForeground(Color.white);
      lblAnio.setBounds(20, 170, 100, 20);
      add(lblAnio);

      txtAnio = new JTextField();
      txtAnio.setBounds(120, 170, 240, 25);
      add(txtAnio);

      btnGuardar = new JButton("Guardar");
      btnGuardar.setBounds(140, 220, 120, 30);
      add(btnGuardar);

      btnGuardar.addActionListener(e -> registrarMeta());
   }

   private void registrarMeta() {
      String nombre = txtNombre.getText().trim();
      String descripcion = txtDescripcion.getText().trim();
      int objetivo, anio;

      try {
         objetivo = Integer.parseInt(txtObjetivo.getText().trim());
         anio = Integer.parseInt(txtAnio.getText().trim());

         Connection cn = Conexion.conectar();
         PreparedStatement pst = cn.prepareStatement(
               "INSERT INTO metas (nombre, descripcion, objetivo, anio) VALUES (?, ?, ?, ?)");
         pst.setString(1, nombre);
         pst.setString(2, descripcion);
         pst.setInt(3, objetivo);
         pst.setInt(4, anio);
         pst.executeUpdate();
         cn.close();

         JOptionPane.showMessageDialog(this, "Meta registrada con éxito.");
         dispose();

      } catch (NumberFormatException nfe) {
         JOptionPane.showMessageDialog(this, "Objetivo y año deben ser números.");
      } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Error al guardar la meta.");
         e.printStackTrace();
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated
   // Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 400, Short.MAX_VALUE));
      layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 300, Short.MAX_VALUE));

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
      // (optional) ">
      /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the default
       * look and feel.
       * For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(CrearMeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(CrearMeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(CrearMeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(CrearMeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      // </editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new CrearMeta().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
}
