/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.MetaDAO;
import clases.MetaObstetra;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moise
 */
public class GestionarMetas extends javax.swing.JFrame {

   /**
    * Creates new form GestionarMetas
    */
   private JTable tablaAvances;
   private JScrollPane scrollPane;


   public GestionarMetas() {
      initComponents();
      getContentPane().setBackground(new Color(60,63,65));
      setTitle("Avance de Metas por Obstetra");
      setSize(700, 400);
      setLocationRelativeTo(null);
      setResizable(false);
      setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

      // Crear la tabla
      tablaAvances = new JTable();
      tablaAvances.setModel(new DefaultTableModel(
            new Object[][] {},
            new String[] { "Obstetra", "Meta", "Avance", "Objetivo", "% Cumplido" }));
      scrollPane = new JScrollPane(tablaAvances);

      // Agregar a la ventana
      getContentPane().setLayout(new BorderLayout());
      getContentPane().add(scrollPane, BorderLayout.CENTER);

      // Cargar datos desde BD
      cargarTablaAvances();
   }

   private void cargarTablaAvances() {
      DefaultTableModel modelo = (DefaultTableModel) tablaAvances.getModel();
      modelo.setRowCount(0); // Limpia la tabla

      ArrayList<MetaObstetra> lista = MetaDAO.obtenerAvances();
      for (MetaObstetra mo : lista) {
         modelo.addRow(new Object[] {
               mo.getNombreObstetra(),
               mo.getNombreMeta(),
               mo.getAvance(),
               mo.getObjetivo(),
               String.format("%.2f %%", mo.getPorcentaje())
         });
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated
   // Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel_Wallpaper = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
      getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
      // (optional) ">
      /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the default
       * look and feel.
       * For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(GestionarMetas.class.getName()).log(java.util.logging.Level.SEVERE, null,
               ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(GestionarMetas.class.getName()).log(java.util.logging.Level.SEVERE, null,
               ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(GestionarMetas.class.getName()).log(java.util.logging.Level.SEVERE, null,
               ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(GestionarMetas.class.getName()).log(java.util.logging.Level.SEVERE, null,
               ex);
      }
      // </editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new GestionarMetas().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel_Wallpaper;
   // End of variables declaration//GEN-END:variables
}
