/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Conexion;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.HashMap;

/**
 *
 * @author moise
 */
public class RegistrarAvance extends javax.swing.JFrame {

   /**
    * Creates new form RegistrarAvance
    */

   private JComboBox<String> comboMetas;
   private JTextField txtAvance;
   private JButton btnGuardar;

   private HashMap<String, Integer> metasMap = new HashMap<>();
   private int idObstetra;

   public RegistrarAvance(int idObstetra) {
      initComponents();
      this.idObstetra = idObstetra;

      setTitle("Registrar Avance");
      setSize(400, 200);
      setLocationRelativeTo(null);
      setLayout(null);
      setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

      JLabel lblMeta = new JLabel("Meta:");
      lblMeta.setBounds(30, 30, 100, 25);
      add(lblMeta);

      comboMetas = new JComboBox<>();
      comboMetas.setBounds(100, 30, 250, 25);
      add(comboMetas);

      JLabel lblAvance = new JLabel("Cantidad:");
      lblAvance.setBounds(30, 70, 100, 25);
      add(lblAvance);

      txtAvance = new JTextField();
      txtAvance.setBounds(100, 70, 100, 25);
      add(txtAvance);

      btnGuardar = new JButton("Guardar");
      btnGuardar.setBounds(140, 110, 120, 30);
      add(btnGuardar);

      btnGuardar.addActionListener(e -> guardarAvance());

      cargarMetas();
      ;
   }

   private void cargarMetas() {
      try {
         Connection cn = Conexion.conectar();
         String sql = "SELECT mo.id, m.nombre FROM meta_obstetra mo " +
               "JOIN metas m ON mo.id_meta = m.id " +
               "WHERE mo.id_obstetra = ?";
         PreparedStatement pst = cn.prepareStatement(sql);
         pst.setInt(1, idObstetra);
         ResultSet rs = pst.executeQuery();

         while (rs.next()) {
            String nombreMeta = rs.getString("nombre");
            int idMetaObstetra = rs.getInt("id");
            comboMetas.addItem(nombreMeta);
            metasMap.put(nombreMeta, idMetaObstetra);
         }

         cn.close();
      } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Error al cargar metas.");
         e.printStackTrace();
      }
   }

   private void guardarAvance() {
      String metaSeleccionada = (String) comboMetas.getSelectedItem();
      String avanceStr = txtAvance.getText().trim();

      if (metaSeleccionada == null || avanceStr.isEmpty()) {
         JOptionPane.showMessageDialog(this, "Completa todos los campos.");
         return;
      }

      int avance;
      try {
         avance = Integer.parseInt(avanceStr);
         if (avance < 0 || avance > 100) {
            throw new NumberFormatException();
         }
      } catch (NumberFormatException ex) {
         JOptionPane.showMessageDialog(this, "Ingresa un avance válido (0 a 100).");
         return;
      }

      int idMetaObstetra = metasMap.get(metaSeleccionada);

      try {
         Connection cn = Conexion.conectar();
         PreparedStatement pst = cn.prepareStatement(
               "UPDATE meta_obstetra SET cantidad_avance = ? WHERE id = ?");
         pst.setInt(1, avance);
         pst.setInt(2, idMetaObstetra);
         pst.executeUpdate();
         cn.close();

         JOptionPane.showMessageDialog(this, "Avance registrado.");
         dispose();
      } catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Error al guardar avance.");
         e.printStackTrace();
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated
   // Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 400, Short.MAX_VALUE));
      layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 300, Short.MAX_VALUE));

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
      // (optional) ">
      /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the default
       * look and feel.
       * For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(RegistrarAvance.class.getName()).log(java.util.logging.Level.SEVERE, null,
               ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(RegistrarAvance.class.getName()).log(java.util.logging.Level.SEVERE, null,
               ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(RegistrarAvance.class.getName()).log(java.util.logging.Level.SEVERE, null,
               ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(RegistrarAvance.class.getName()).log(java.util.logging.Level.SEVERE, null,
               ex);
      }
      // </editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new RegistrarAvance(1).setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   // End of variables declaration//GEN-END:variables
}
